### 일정 조회
GET http://localhost:8080/api/v1/schedules
Access-Token: Bearer eyJkYXRlIjoxNzE4NjIzNTEzNjg0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcElkIjoidXNlcjAyIiwiZW1wUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTIyODMxM30.Ybw18HxmQcr96dGCGlcvgSdhGI1yLo3ymp10kKUtPV-OJzzwEoeTLZKffdhFtfQjLj-qATxbJ6cWQ4uJAFDftA

### 일정 등록
POST http://localhost:8080/api/v1/schedules/regist
Content-Type: application/json
Access-Token: Bearer eyJkYXRlIjoxNzE4NjIzNTEzNjg0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcElkIjoidXNlcjAyIiwiZW1wUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTIyODMxM30.Ybw18HxmQcr96dGCGlcvgSdhGI1yLo3ymp10kKUtPV-OJzzwEoeTLZKffdhFtfQjLj-qATxbJ6cWQ4uJAFDftA

{
  "schName": "월간회의",
  "schPlace": "2층 대회의실",
  "schDescription": "6월 월간회의 2층 대회의실에서 진행합니다.",
  "schSdatetime": "2024-06-05T10:00:00",
  "schEdatetime": "2024-06-05T12:00:00",
  "schAllday": "Y",
  "schSharing": "all",
  "schColor": "#123456",
  "schWriter": "2",
  "schStatus": "ACTIVE"
}

### 일정 수정
PUT http://localhost:8080/api/v1/schedules/3
Content-Type: application/json
Access-Token: Bearer eyJkYXRlIjoxNzE4NjIzNTEzNjg0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcElkIjoidXNlcjAyIiwiZW1wUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTIyODMxM30.Ybw18HxmQcr96dGCGlcvgSdhGI1yLo3ymp10kKUtPV-OJzzwEoeTLZKffdhFtfQjLj-qATxbJ6cWQ4uJAFDftA

{
  "schName": "월간회의",
  "schPlace": "2층 대회의실",
  "schSdatetime": "2024-06-05 10:00:00",
  "schEdatetime": "2024-06-05 12:00:00",
  "schAllday": "Y",
  "schSharing": "project",
  "schColor": "#123456",
  "schWriter": "2",
  "schStatus": "ACTIVE"
}

### 일정 삭제
DELETE http://localhost:8080/api/v1/schedules/3
Content-Type: application/json
Access-Token: Bearer eyJkYXRlIjoxNzE4NjIzNTEzNjg0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcElkIjoidXNlcjAyIiwiZW1wUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxOTIyODMxM30.Ybw18HxmQcr96dGCGlcvgSdhGI1yLo3ymp10kKUtPV-OJzzwEoeTLZKffdhFtfQjLj-qATxbJ6cWQ4uJAFDftA
